# -*- coding: utf-8 -*-
"""main_v5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4LSNABaTSmXD4XW2Eht0pbRUnen_EtK
"""

# !git clone https://wayo116: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@github.com/wayo116/2306_l6.git

import os
import csv
import time

from datalists import dlists
from Dell6_v2 import Dell6
from Utility.LightgbmPack import LightgbmPack

start = time.time()

csv_dir = 'result.csv'
with open(csv_dir, "a", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["kaisai",
        "saisinkekka_list",
        "predictions",
        "l1l2_len",
        "predictions_len",
        "percent" 
        ])

# kaisai = 50
lgbm_obj = LightgbmPack(makecsv=False)

for kaisai in range(1,6):
    if kaisai == -1:
        #本番
        #最新結果がgitjubに登録済の時
        saisinkekka_list=[99,99,99,99,99,99]
        dlists = dlists
    elif kaisai == 0:
        #最新結果がcolabにはあるが、gitjubには未登録の時
        saisinkekka_list=[2,10,27,38,40,41]
        dlists = dlists
    elif kaisai > 0:
        saisinkekka_list = dlists[kaisai-1]
        dlists = dlists[kaisai:]
    print("saisinkekka_list",saisinkekka_list)
    print("dlists",dlists[:5])

    predictions_all = []

    print('\n----vol 1----')
    params = {"train_params":{"range_start": 1,
                       "range_end":11,
                       "yousosu":10,
                       "multisu":1,
                       "randomkeisu":112,
                       "nmasi":3},
        "test_params":{"range_start": 1,
                       "range_end":11,
                       "yousosu":10,
                       "multisu":1,
                       "randomkeisu":112,
                       "nmasi":1}}
    
    predictions = lgbm_obj.lightgbmpack(kaisai, saisinkekka_list, dlists, **params)
    predictions_all.extend(predictions)

    print('\n----vol 2----')
    params = {"train_params":{"range_start": 11,
                       "range_end":21,
                       "yousosu":10,
                       "multisu":1,
                       "randomkeisu":112,
                       "nmasi":3},
        "test_params":{"range_start": 11,
                       "range_end":21,
                       "yousosu":10,
                       "multisu":1,
                       "randomkeisu":112,
                       "nmasi":1}}
    
    predictions = lgbm_obj.lightgbmpack(kaisai, saisinkekka_list, dlists, **params)
    predictions_all.extend(predictions)

    print('\n----vol 3----')
    params = {"train_params":{"range_start": 21,
                       "range_end":31,
                       "yousosu":10,
                       "multisu":1,
                       "randomkeisu":112,
                       "nmasi":3},
        "test_params":{"range_start": 21,
                       "range_end":31,
                       "yousosu":10,
                       "multisu":1,
                       "randomkeisu":112,
                       "nmasi":1}}
    
    predictions = lgbm_obj.lightgbmpack(kaisai, saisinkekka_list, dlists, **params)
    predictions_all.extend(predictions)


    print("saisinkekka_list",saisinkekka_list)
    predictions_all = sorted(list(map(int, set(predictions_all))))
    print("predictions_all_set",predictions_all)

    l1 = saisinkekka_list
    l2 = predictions_all
    l1_l2_and = set(l1) & set(l2)
    l1l2_len = len(l1_l2_and)
    predictions_len = len(predictions_all)

    percent = round(l1l2_len/predictions_len*100)
    print("percent",percent)
    print("\n")

    with open(csv_dir, "a", newline="") as file:
        writer = csv.writer(file)
        writer.writerow([kaisai,
            saisinkekka_list,
            predictions_all,
            l1l2_len,
            predictions_len,
            percent,
            ])

print("処理時間",time.time() - start)

