# -*- coding: utf-8 -*-
"""main_v6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POOwXUJfCtoLLXsqCVeTOaOcoutumX8Y
"""

!git clone https://wayo116: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@github.com/wayo116/2306_l6.git

import os
import csv
import time

os.chdir('/content/2306_l6')

from datalists import dlists
from Utility.inner_outer import combi
from Dell6_v2 import Dell6
from Utility.LightgbmPack import LightgbmPack

start = time.time()

kaisai = -1
if kaisai == -1:
    #本番
    #最新結果がgitjubに登録済の時
    saisinkekka_list=[99,99,99,99,99,99]
    dlists = dlists
elif kaisai == 0:
    #最新結果がcolabにはあるが、gitjubには未登録の時
    saisinkekka_list=[9,11,12,14,27,38]
    dlists = dlists
elif kaisai > 0:
    saisinkekka_list = dlists[kaisai-1]
    dlists = dlists[kaisai:]
print("saisinkekka_list",saisinkekka_list)
print("dlists",dlists[:5])


bunkatu=5
predictions_all = []
lgbm_obj = LightgbmPack(makecsv=False)

print('\n----vol 1----')
params = {"train_params":{"range_start": 1,
                    "range_end":11,
                    "yousosu":10,
                    "multisu":1,
                    "randomkeisu":112,
                    "nmasi":3},
    "test_params":{"range_start": 1,
                    "range_end":11,
                    "yousosu":10,
                    "multisu":1,
                    "randomkeisu":112,
                    "nmasi":1}}

predictions = lgbm_obj.lightgbmpack(kaisai, saisinkekka_list, dlists, **params)
predictions_all.extend(predictions)

print('\n----vol 2----')
params = {"train_params":{"range_start": 11,
                    "range_end":21,
                    "yousosu":10,
                    "multisu":1,
                    "randomkeisu":112,
                    "nmasi":3},
    "test_params":{"range_start": 11,
                    "range_end":21,
                    "yousosu":10,
                    "multisu":1,
                    "randomkeisu":112,
                    "nmasi":1}}

predictions = lgbm_obj.lightgbmpack(kaisai, saisinkekka_list, dlists, **params)
predictions_all.extend(predictions)

print('\n----vol 3----')
params = {"train_params":{"range_start": 21,
                    "range_end":31,
                    "yousosu":10,
                    "multisu":1,
                    "randomkeisu":112,
                    "nmasi":3},
    "test_params":{"range_start": 21,
                    "range_end":31,
                    "yousosu":10,
                    "multisu":1,
                    "randomkeisu":112,
                    "nmasi":1}}

predictions = lgbm_obj.lightgbmpack(kaisai, saisinkekka_list, dlists, **params)
predictions_all.extend(predictions)


print("saisinkekka_list",saisinkekka_list)
predictions_all = sorted(list(map(int, set(predictions_all))))
print("predictions_all_set",predictions_all)

pred_dlists = combi(predictions_all,6)

#shori2は、pred_dlistsには組合せリストを入れる
outlist=Dell6(dlists, pred_dlists, saisinkekka_list, bunkatu).shori2()
#outlists.extend(outlist)
#print('outlist',outlist)

print("処理時間",time.time() - start)